# Generated by Django 3.0.3 on 2020-08-08 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tickets', '0002_berth_coach_gender_passenger_tickettype'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='child',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='berth_preference',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='coach',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ticket_type',
            field=models.CharField(max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='passengerdetails',
            name='berth_preference',
            field=models.CharField(choices=[('UPR', 'Upper'), ('LWR', 'Lower'), ('MID', 'Middle'), ('SID', 'Side Portion')], max_length=50),
        ),
        migrations.AlterField(
            model_name='tickettype',
            name='name',
            field=models.CharField(max_length=36),
        ),
    ]
