# Generated by Django 3.0.3 on 2020-08-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tickets', '0003_auto_20200808_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='berth_preference',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='coach',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='passenger',
            name='ticket_type',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
